[tool.poetry]
name = "pyclingo"
version = "0.1.0"
description = ""
authors = ["Jolyon Bloomfield <jkb84@cornell.edu>"]

[tool.poetry.dependencies]
python = "^3.11"
ruff = "^0.11.8"
mypy = "^1.15.0"
pyright = "^1.1.400"
clingo = "^5.8.0"
pre-commit = "^4.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
strict_optional = true
files = ["pyclingo", "aspuzzle"]

[tool.pyright]
include = [
  "pyclingo",
  "aspuzzle",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "W", "Q", "I"]
fixable = ["ALL"]

[tool.ruff.lint.isort]
known-first-party = ["pyclingo"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
