"""
Grounding analysis: the statement and signature profilers.

Where the grounding's size and work come from, joined back to authoring
Python lines. GroundedProgram's grounding_profile()/analyze_grounding()
and statement_profile()/analyze_statements() are thin entrypoints over
this module: signature profiling reads the grounded atom base directly;
statement profiling re-grounds an instrumented copy of the program and
counts each statement's ground instantiations with an observer. The
instrumentation contract — what is counted, what passes through, and the
honest limits — is documented on the entrypoints and in
docs/diagnostics.md ("Profiling by statement").

Note: This file is enttirely generated by Claude.
"""

import itertools
import re
from collections.abc import Iterator, Mapping, Sequence
from dataclasses import dataclass

import clingo

from aspalchemy.choice import Choice
from aspalchemy.optimization import WeakConstraint
from aspalchemy.program_elements import RawASP, RenderedLine, Rule, masked_spans, skip_string
from aspalchemy.source_location import SourceLocation


@dataclass(frozen=True)
class SignatureGrounding:
    """
    One row of a grounding profile: a signature's ground atom count and
    the statements that derive it. derived_at holds authoring locations,
    deduplicated in document order; None stands for a statement whose
    segment had source locations switched off, and an empty tuple means
    no aspalchemy statement derives the signature (e.g. raw-text atoms
    declared only via show()).
    """

    name: str
    arity: int
    atom_count: int
    derived_at: tuple[SourceLocation | None, ...]


@dataclass(frozen=True)
class StatementGrounding:
    """
    One row of a statement profile: a statement's ground instantiation
    count and its provenance. statement is the rendered ASP text;
    location is the authoring Python line, or None where its segment had
    source locations switched off. instances counts the statement's
    ground instantiations BEFORE fact-propagation simplification — the
    work gringo performs, not the statements that survive it (the two
    coincide except where fact folding erases rules).
    """

    statement: str
    location: SourceLocation | None
    instances: int


# The statement profiler's marker predicate: appended to each statement's
# body in an instrumented re-ground, so every ground instantiation carries
# its statement's rendered line number. The name is aspalchemy-reserved.
_STATEMENT_MARKER = "__aspalchemy_stmt"
_FACT_COMPANION = "__aspalchemy_fact"
# Weak statements count by minimize entries at a reserved priority:
# base + rendered line number, far above any real program's priorities
_WEAK_PRIORITY_BASE = 10_000_000
_IDENTIFIER_CHARS = frozenset("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_'")


class _BodyLiteralObserver(clingo.Observer):
    """
    Ground-program observer: the statement profiler's counting channels.
    Rules and facts count by a marker literal riding their bodies once per
    ground instantiation (the declaring choice has an empty body, so
    markers count exactly the instantiations). Weak constraints count by
    entries at their statement's reserved priority — gringo's minimize
    callback preserves one entry per ground tuple, undeduplicated, so the
    weak body itself is never touched and grounds exactly as the real
    program.
    """

    def __init__(self) -> None:
        self.body_counts: dict[int, int] = {}
        self.priority_counts: dict[int, int] = {}

    def rule(self, choice: bool, head: Sequence[int], body: Sequence[int]) -> None:
        for literal in body:
            if literal > 0:
                self.body_counts[literal] = self.body_counts.get(literal, 0) + 1

    def minimize(self, priority: int, literals: Sequence[tuple[int, int]]) -> None:
        self.priority_counts[priority] = self.priority_counts.get(priority, 0) + len(literals)


def _has_rule_arrow(statement: str) -> bool:
    """Whether the statement text contains ':-' outside string literals."""
    i, n = 0, len(statement)
    while i < n:
        if statement[i] == '"':
            i = skip_string(statement, i)
        elif statement.startswith(":-", i):
            return True
        else:
            i += 1
    return False


def _split_line_comment(line: str) -> tuple[str, str]:
    """
    Split a line at its trailing '%' comment, judged outside string
    literals: (code, comment tail). A line with no comment returns
    (line, "").
    """
    i, n = 0, len(line)
    while i < n:
        if line[i] == '"':
            i = skip_string(line, i)
        elif line[i] == "%":
            return line[:i], line[i:]
        else:
            i += 1
    return line, ""


def _statement_complete(stripped: str) -> bool:
    """
    Whether a raw line ENDS a statement: a terminating '.' — but not the
    '..' of a range split across lines — or the ']' closing a weak
    constraint's '[weight@priority]' tail, on whichever line it falls.
    """
    if stripped.endswith("]"):
        return True
    return stripped.endswith(".") and not stripped.endswith("..")


def _rename_anonymous(statement: str, next_index: Iterator[int]) -> str:
    """
    Every anonymous variable '_' replaced with a fresh reserved named
    variable (each occurrence distinct) — EXCEPT inside default-negated
    literals, where the rename would create an unsafe variable ('not
    p(_)' is legal; 'not p(V)' with V nowhere else is not) and where
    projection carries no join work to hide anyway. Elsewhere, gringo's
    projection rewrite would hide a statement's join work from the
    profiler's marker; named apart, the join grounds in the open and the
    marker rides every instantiation.
    """
    out: list[str] = []
    i, n = 0, len(statement)
    depth = 0
    negated_at: int | None = None  # bracket depth where the current 'not' literal began
    while i < n:
        char = statement[i]
        if char == '"':
            end = skip_string(statement, i)
            out.append(statement[i:end])
            i = end
            continue
        if char in "({[":
            depth += 1
        elif char in ")}]":
            depth -= 1
            if negated_at is not None and depth < negated_at:
                negated_at = None
        elif negated_at is not None and depth == negated_at and char in ",;:.":
            negated_at = None
        elif (
            statement.startswith("not", i)
            and (i == 0 or statement[i - 1] not in _IDENTIFIER_CHARS)
            and (i + 3 == n or statement[i + 3] not in _IDENTIFIER_CHARS)
        ):
            if negated_at is None:
                negated_at = depth
            out.append("not")
            i += 3
            continue
        elif (
            char == "_"
            and negated_at is None
            and (i == 0 or statement[i - 1] not in _IDENTIFIER_CHARS)
            and (i + 1 == n or statement[i + 1] not in _IDENTIFIER_CHARS)
        ):
            out.append(f"ASPALCHEMY_ANON{next(next_index)}")
            i += 1
            continue
        out.append(char)
        i += 1
    return "".join(out)


def _split_weak_tail(statement: str) -> tuple[str, str] | None:
    """
    A weak constraint split at the LAST '. [' outside string literals:
    (head ending before the dot, tail starting at '['), or None if no
    such delimiter exists outside strings.
    """
    i, n = 0, len(statement)
    last: int | None = None
    while i < n:
        if statement[i] == '"':
            i = skip_string(statement, i)
        elif statement.startswith(". [", i):
            last = i
            i += 3
        else:
            i += 1
    if last is None:
        return None
    return statement[:last], statement[last + 2 :]


def _rewrite_weak_priority(tail: str, priority: int) -> str | None:
    """
    The '[weight@priority, terms]' tail with its priority replaced by the
    profiler's reserved value — or None when the tail's priority is not a
    plain integer (a variable priority cannot be redirected). The weight
    segment ends at the first ',' or ']' outside strings and brackets;
    '@' inside it marks an explicit priority.
    """
    i, n = 1, len(tail)  # tail[0] == "["
    depth = 0
    at: int | None = None
    end = n - 1
    while i < n:
        char = tail[i]
        if char == '"':
            i = skip_string(tail, i)
            continue
        if char in "({[":
            depth += 1
        elif char in ")}]":
            if depth == 0:
                end = i
                break
            depth -= 1
        elif depth == 0 and char == ",":
            end = i
            break
        elif depth == 0 and char == "@":
            at = i
        i += 1
    if at is None:
        return f"{tail[:end]}@{priority}{tail[end:]}"
    declared = tail[at + 1 : end].strip()
    if not declared.removeprefix("-").isdigit():
        return None
    return f"{tail[: at + 1]}{priority}{tail[end:]}"


def _interior_statement_dot(core: str) -> bool:
    """
    Whether the statement core (final '.' already stripped) contains a
    statement-terminating '.' outside strings — i.e. the line holds more
    than one statement, which line-based raw attribution cannot tag.
    Range '..' tokens are not terminators.
    """
    i, n = 0, len(core)
    while i < n:
        char = core[i]
        if char == '"':
            i = skip_string(core, i)
        elif char == ".":
            if i + 1 < n and core[i + 1] == ".":
                i += 2
            else:
                return True
        else:
            i += 1
    return False


def _top_level_head_syntax(core: str) -> bool:
    """
    Whether a bodiless raw statement uses head-level ';' (disjunction),
    ':' (conditional head), or '{' (a choice, including cardinality-
    bounded forms like '1 { p } 2') outside strings and brackets — shapes
    the fact companion cannot wrap (a term argument reinterprets or
    rejects them), so they gate instead.
    """
    i, n = 0, len(core)
    depth = 0
    while i < n:
        char = core[i]
        if char == '"':
            i = skip_string(core, i)
            continue
        if char == "{" and depth == 0:
            return True
        if char in "({[":
            depth += 1
        elif char in ")}]":
            depth -= 1
        elif depth == 0 and char in ";:":
            return True
        i += 1
    return False


def _contiguous_runs(numbers: list[int]) -> Iterator[tuple[int, int]]:
    """Sorted line numbers as inclusive (start, end) runs."""
    index = 0
    while index < len(numbers):
        start = numbers[index]
        while index + 1 < len(numbers) and numbers[index + 1] == numbers[index] + 1:
            index += 1
        yield start, numbers[index]
        index += 1


def _instrument_source(
    text: str,
    statement_table: Mapping[int, tuple[str, SourceLocation | None, str]],
    raw_locations: Mapping[int, SourceLocation | None],
) -> tuple[str, dict[int, tuple[str, SourceLocation | None, str]]]:
    """
    The source instrumented for the statement profile, plus the tagged
    line -> (statement text, authoring location, counting channel) map.

    Per statement kind:
    - "fact": the fact stays a REAL fact — untouched, so aggregate
      evaluation over facts matches the true grounding exactly — and a
      COMPANION rule __aspalchemy_fact(<head>) :- marker. is appended,
      whose pool expansion instantiates once per fact instance with the
      marker riding each. A classically negated head sheds its sign for
      the companion argument (the count is sign-independent).
    - "choice_fact": gated with ':- marker' (choice atoms are open in the
      real grounding too, so gating changes nothing evaluable).
    - "rule": '; marker' appended — the separator a trailing conditional
      literal's condition cannot absorb.
    - "weak": the BODY is left untouched — it grounds exactly as the real
      program — and the tail's priority is redirected to a reserved value
      (_WEAK_PRIORITY_BASE + line), where gringo's minimize callback
      reports one entry per ground tuple. A weak whose priority is not a
      plain integer (unreachable from the renderer) stays uncounted.

    Anonymous variables in marker-carrying statements are renamed apart
    (see _rename_anonymous) so gringo's projection cannot hide a
    statement's join work from the marker; occurrences under default
    negation are left alone (renaming them would be unsafe). Markers are
    declared in one bare choice so they stay undecided at ground time.

    Classification is STRUCTURAL for everything the renderer produced.
    Only raw_asp blocks — arbitrary text by contract — take the residual
    line-based pass: run-local comment and #script spans are skipped
    (correct across adjacent blocks because raw_asp() enforces lexical
    self-containment), a trailing '%' comment splits off and is
    preserved, a statement opened on one line suppresses tagging until
    the line that closes it (a '..' range split counts as open), a
    '[...]' line is a weak tail continuation, and lines the pass cannot
    honestly attribute — several statements sharing one line, or
    multi-line statements — pass through untouched and uncounted, as
    documented. Bodiless raw statements with head-level ';' or ':' are
    gated rather than companioned.
    """
    lines = text.split("\n")
    out = list(lines)
    trailing: list[str] = []
    tagged: dict[int, tuple[str, SourceLocation | None, str]] = {}
    # Fresh anonymous-variable names must not capture existing ones: start
    # past any ASPALCHEMY_ANON suffix already present in the source
    start = 0
    for match in re.finditer(r"ASPALCHEMY_ANON(\d+)", text):
        start = max(start, int(match.group(1)) + 1)
    anon_index = itertools.count(start)

    def instrument(number: int, statement: str, kind: str, location: SourceLocation | None, comment: str = "") -> None:
        marker = f"{_STATEMENT_MARKER}({number})"
        if kind == "weak":
            split = _split_weak_tail(statement)
            rewritten_tail = None if split is None else _rewrite_weak_priority(split[1], _WEAK_PRIORITY_BASE + number)
            if split is not None and rewritten_tail is not None:
                out[number - 1] = f"{split[0]}. {rewritten_tail}"
                tagged[number] = (statement, location, "weak")
            # An unredirectable tail (a variable priority — unreachable from
            # the renderer, whose priorities are integers) stays uncounted
            # rather than perturbed
            return
        core = statement[:-1].rstrip()
        if kind == "fact":
            trailing.append(f"{_FACT_COMPANION}({core.lstrip('-')}) :- {marker}.")
        elif kind == "choice_fact":
            rewritten = f"{_rename_anonymous(core, anon_index)} :- {marker}."
            out[number - 1] = f"{rewritten} {comment}" if comment else rewritten
        else:
            rewritten = f"{_rename_anonymous(core, anon_index)}; {marker}."
            out[number - 1] = f"{rewritten} {comment}" if comment else rewritten
        tagged[number] = (statement, location, kind)

    for number, (statement, location, kind) in statement_table.items():
        instrument(number, statement, kind, location)

    for run_start, run_end in _contiguous_runs(sorted(raw_locations)):
        block_lines = lines[run_start - 1 : run_end]
        block_text = "\n".join(block_lines)
        masked_block_lines: set[int] = set()
        for span_start, span_end in masked_spans(block_text):
            first = block_text.count("\n", 0, span_start) + 1
            last = block_text.count("\n", 0, span_end) + 1
            masked_block_lines.update(range(first, last + 1))
        continuation = False
        for offset, line in enumerate(block_lines, start=1):
            if offset in masked_block_lines:
                continue
            code, comment = _split_line_comment(line)
            stripped = code.strip()
            if not stripped:
                continue
            if stripped.startswith("[") and stripped.endswith("]"):
                continue  # a weak tail on its own line: not a statement, not a continuation
            if continuation:
                continuation = not _statement_complete(stripped)
                continue
            if stripped.startswith(("#", ":~")) or not (stripped.endswith(".") and not stripped.endswith("..")):
                continuation = not _statement_complete(stripped)
                continue
            core = stripped[:-1].rstrip()
            if _interior_statement_dot(core):
                continue  # several statements share this line: uncounted, documented
            number = run_start + offset - 1
            if stripped.startswith("{"):
                kind = "choice_fact"
            elif _has_rule_arrow(core):
                kind = "rule"
            elif _top_level_head_syntax(core):
                kind = "choice_fact"  # disjunctive or conditional head: gate, never companion
            else:
                kind = "fact"
            instrument(number, stripped, kind, raw_locations[number], comment.strip())

    if tagged:
        trailing.append("{" + ";".join(f"{_STATEMENT_MARKER}({number})" for number in sorted(tagged)) + "}.")
    return "\n".join(out + trailing) + "\n", tagged


def classify_statements(
    lines: Sequence[RenderedLine],
) -> tuple[dict[int, tuple[str, SourceLocation | None, str]], dict[int, SourceLocation | None]]:
    """
    The statement profiler's structural classification of a render: a
    line -> (statement text, location, kind) table for every rendered
    Rule and WeakConstraint — the render's element column knows
    statement-ness, fact-ness, and choice-ness, so nothing is re-derived
    from text — plus the raw-block line map that takes the residual
    textual pass.
    """
    statement_table: dict[int, tuple[str, SourceLocation | None, str]] = {}
    raw_locations: dict[int, SourceLocation | None] = {}
    for line_number, line in enumerate(lines, start=1):
        element = line.element
        if isinstance(element, Rule):
            if element.body:
                kind = "rule"
            elif isinstance(element.head, Choice):
                kind = "choice_fact"
            else:
                kind = "fact"
            statement_table[line_number] = (line.text.strip(), element.source_location, kind)
        elif isinstance(element, WeakConstraint):
            statement_table[line_number] = (line.text.strip(), element.source_location, "weak")
        elif isinstance(element, RawASP):
            raw_locations[line_number] = element.source_location
    return statement_table, raw_locations


def grounding_profile(
    control: clingo.Control,
    derivation_sites: Mapping[tuple[str, int], tuple[SourceLocation | None, ...]],
) -> tuple[SignatureGrounding, ...]:
    """
    Where the grounding's size comes from, as data: one
    SignatureGrounding per signature, largest atom count first, each
    joined to the statements that derive it. Counts are gringo's
    ground truth (atoms simplified away at grounding are already
    gone; both signs of a signature count together).
    analyze_grounding() renders exactly this as prose.
    """
    counts: dict[tuple[str, int], int] = {}
    for name, arity, positive in control.symbolic_atoms.signatures:
        tally = sum(1 for _ in control.symbolic_atoms.by_signature(name, arity, positive=positive))
        counts[(name, arity)] = counts.get((name, arity), 0) + tally
    profile: list[SignatureGrounding] = []
    for (name, arity), count in sorted(counts.items(), key=lambda item: (-item[1], item[0])):
        deduped: list[SourceLocation | None] = []
        for site in derivation_sites.get((name, arity), ()):
            if site not in deduped:
                deduped.append(site)
        profile.append(SignatureGrounding(name, arity, count, tuple(deduped)))
    return tuple(profile)


def analyze_grounding(profile: tuple[SignatureGrounding, ...]) -> str:
    """
    The grounding profile as prose: ground atom counts per signature,
    largest first, each joined to the authoring lines that derive it.
    The first stop when grounding is slow or huge — the top rows name
    the lines to rethink. grounding_profile() is the same data,
    structured.

    One blind spot, stated plainly: the report joins on HEADS, so a
    statement whose body grounds large without deriving new atoms
    (a wide joint feeding a small head) shows up under its head's
    count, not as its own row. statement_profile() charges every
    statement its own row — constraints and weak constraints
    included — leaving only minimize()/maximize() directives
    unattributed.
    """
    total = sum(entry.atom_count for entry in profile)
    lines = [f"Grounding profile: {total} ground atoms across {len(profile)} signatures"]
    for entry in profile:
        described = [
            site.display() if site is not None else "unknown (source locations off)" for site in entry.derived_at
        ]
        origin = ", ".join(described) if described else "no aspalchemy statement (declared but underived?)"
        lines.append(f"  {entry.name}/{entry.arity}: {entry.atom_count} atoms — derived at {origin}")
    return "\n".join(lines)


def statement_profile(
    text: str,
    statement_table: Mapping[int, tuple[str, SourceLocation | None, str]],
    raw_locations: Mapping[int, SourceLocation | None],
    grounding_context: object,
) -> tuple[StatementGrounding, ...]:
    """
    Where the grounding's WORK comes from, as data: one
    StatementGrounding per statement, largest instantiation count
    first. Where grounding_profile() counts the atoms each signature
    ends up with, this counts the ground INSTANCES each statement
    produces — so constraints and wide-bodied rules, invisible to a
    head-joined profile, charge their own rows. analyze_statements()
    renders exactly this as prose.

    How: an instrumented re-ground, counted by a ground-program
    observer — no text is ever parsed, and statements are classified
    structurally from the render (a comment or directive can never be
    mistaken for one); only raw_asp text takes a line-based pass.
    Facts stay REAL facts, counted by a companion rule whose pool
    expansion instantiates once per fact instance, so aggregates over
    facts evaluate exactly as the true grounding. Rules carry a
    reserved marker literal in their bodies (choice statements gate
    on it), kept undecided by a bare choice so fact propagation
    cannot fold instantiations away. Weak constraints' bodies are
    untouched: only their priority is redirected to a reserved value,
    where the minimize callback reports one entry per ground tuple.
    Anonymous variables are renamed apart so projection cannot hide a
    statement's join work — except under default negation, where
    renaming would be unsafe. Consequences, stated plainly:

    - Counts are the instantiations gringo emits per statement, kept
      visible past the final fact-folding. minimize()/maximize()
      directives are the one excluded statement kind, and an
      assignment aggregate over atoms DERIVED from facts charges an
      upper bound (its domain is open in the instrumented copy),
      while aggregates directly over facts are exact.
    - Each call pays a full in-process re-ground, with
      ground_text()'s stateful-context divergence caveat (a context
      answering differently on the second call skews or breaks the
      profile) — but no threading caveat: no file descriptors are
      rebound.
    - Every rendered aspalchemy statement except optimization
      directives is counted. In raw_asp text, attribution is
      line-based: statements spanning several lines, several sharing
      one line, sharing a line with a block comment, and raw weak
      constraints and directives all pass through uncounted.
    """
    instrumented, tagged = _instrument_source(text, statement_table, raw_locations)
    if not tagged:
        return ()
    counts = _count_marker_instances(instrumented, tagged, grounding_context)
    rows = [
        StatementGrounding(statement=statement, location=location, instances=counts[line])
        for line, (statement, location, _channel) in tagged.items()
    ]
    rows.sort(key=lambda row: (-row.instances, row.statement))
    return tuple(rows)


def _count_marker_instances(
    instrumented: str,
    tagged: Mapping[int, tuple[str, SourceLocation | None, str]],
    grounding_context: object,
) -> dict[int, int]:
    """
    Ground the instrumented source on a fresh in-process Control with
    the counting observer. Marker-carrying statements read their count
    back through symbolic_atoms (total over the whole atom base — the
    output table cannot resolve markers, since the program's #show
    block hides them); weak statements read the minimize-entry count
    at their reserved priority.
    """
    observer = _BodyLiteralObserver()
    messages: list[str] = []
    control = clingo.Control(logger=lambda _code, message: messages.append(message), message_limit=50)
    control.register_observer(observer)
    try:
        control.add("base", [], instrumented)
        control.ground([("base", [])], context=grounding_context)
    except RuntimeError as error:
        tail = "\n".join(messages[-3:]) if messages else str(error)
        raise RuntimeError(
            f"instrumented re-grounding for the statement profile failed although the "
            f"original ground() succeeded — a stateful @-function context answering "
            f"differently on the second call is the usual cause; a raw_asp construct "
            f"the line-based instrumentation mishandles is another. clingo reported:\n{tail}"
        ) from error
    counts: dict[int, int] = {}
    for number, (_statement, _location, channel) in tagged.items():
        if channel == "weak":
            counts[number] = observer.priority_counts.get(_WEAK_PRIORITY_BASE + number, 0)
            continue
        symbol = clingo.Function(_STATEMENT_MARKER, [clingo.Number(number)])
        atom = control.symbolic_atoms[symbol]
        counts[number] = 0 if atom is None else observer.body_counts.get(atom.literal, 0)
    return counts


def analyze_statements(profile: tuple[StatementGrounding, ...]) -> str:
    """
    The statement profile as prose: ground instantiation counts per
    statement, largest first, each with its authoring line. The
    per-statement complement to analyze_grounding() — no head-join
    blind spot, at the price of one instrumented re-ground per call
    (see statement_profile() for exactly what is counted).
    """
    total = sum(entry.instances for entry in profile)
    lines = [f"Statement profile: {total} ground instantiations across {len(profile)} statements"]
    for entry in profile:
        origin = entry.location.display() if entry.location is not None else "unknown (source locations off)"
        statement = entry.statement if len(entry.statement) <= 80 else entry.statement[:77] + "..."
        lines.append(f"  {entry.instances:>10}  {statement}  — {origin}")
    return "\n".join(lines)
