"""
aspalchemy's exception types.

Almost everything in aspalchemy raises builtins: ValueError for invalid
programs and inputs, TypeError for wrong types, RuntimeError for misuse
guards, TimeoutError for deadlines. A class lives here only where a
builtin is too broad a catch target.
"""

from collections.abc import Sequence
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from aspalchemy.clingo_handler import ClingoMessage
    from aspalchemy.core import DefaultNegation
    from aspalchemy.predicate import Predicate


class ASPAlchemyError(Exception):
    """
    The root of aspalchemy's dedicated exceptions. Catching it nets every
    exception CLASS aspalchemy defines — not every error aspalchemy raises:
    validation and misuse failures deliberately stay on builtins (see the
    module docstring).
    """


class GroundingError(ASPAlchemyError):
    """
    clingo rejected the rendered program: a parse error, a grounding
    failure, or diagnostics at or above the stop threshold. Raised by
    ground() and every verb that grounds (solve, cautious, brave,
    optimize). The message carries clingo's diagnostics, each with a
    "generated by file:line" note pointing at the authoring Python line;
    .messages holds the same diagnostics structured (a ClingoMessage
    tuple, empty when the failure produced none).
    """

    def __init__(self, message: str, messages: Sequence[ClingoMessage] = ()) -> None:
        super().__init__(message)
        self.messages = tuple(messages)


class UnsatisfiableError(ASPAlchemyError):
    """
    The program has no answer set, raised where an answer was required:
    first() and the eager verbs (cautious, brave, optimize). The one
    exception reporting an OUTCOME rather than a mistake — catch it to
    branch on UNSAT, or use a stream, which never raises it: solve() and
    the _iter twins report UNSAT by yielding nothing (check .satisfiable
    or .exhausted on the handle).

    Carries the search's evidence: .unsat_core is the conflicting
    assumptions in the shapes they were given (() when UNSAT needed no
    assumptions; None when the raising verb had no core to report), and
    .messages is the solve's structured ClingoMessage tuple.
    """

    def __init__(
        self,
        message: str,
        unsat_core: tuple[Predicate | DefaultNegation, ...] | None = None,
        messages: Sequence[ClingoMessage] = (),
    ) -> None:
        super().__init__(message)
        self.unsat_core = unsat_core
        self.messages = tuple(messages)
