% Sudoku puzzle solver by ASPuzzle
% Generated by pyclingo on 2025-05-27 09:44:08

% ===== Grid =====

% Define cells in the grid
cell(R, C) :- R = 1..4, C = 1..4.

% Define major lines in the grid
line("e", R, cell(R, C)) :- cell(R, C), R = 1..4.
line("s", C, cell(R, C)) :- cell(R, C), C = 1..4.

% ===== Symbols =====

% Place symbols in the grid
{ number(cell(R, C), V) : V = 1..4 } = 1 :- cell(R, C).

% ===== Rules =====

% Each digit appears at most once in each row and column
C1 = C2 :- number(C1, N), number(C2, N), line(D, Idx, C1), line(D, Idx, C2).

% Define block membership
block(cell(R, C), N) :- cell(R, C), N = 1 + (C - 1) / 2 + 2 * ((R - 1) / 2).

% Each digit appears at most once in each block
C1 = C2 :- number(C1, N), number(C2, N), block(C1, Idx), block(C2, Idx).

% ===== Clues =====
number(cell(1, 2), 3).
number(cell(1, 4), 2).
number(cell(2, 3), 4).
number(cell(2, 4), 3).
number(cell(3, 1), 2).
number(cell(3, 3), 3).
number(cell(4, 1), 3).
number(cell(4, 2), 4).

#show.
#show number/2.
