"""
Tests for clingo message parsing and severity handling.
"""

import dataclasses

import clingo
import pytest

from pyclingo import ASPProgram, GroundingError, LogLevel, Predicate, SourceLocation
from pyclingo.clingo_handler import ClingoMessageHandler


def test_multiline_location_span_parses() -> None:
    # Location spans may cross lines (L:C-L:C); severity must still be read
    handler = ClingoMessageHandler("line one\nline two", stop_on_level=LogLevel.ERROR)
    handler.on_message(None, "<block>:1:10-2:5: error: something spans lines")  # type: ignore[arg-type]
    assert handler.highest_level == LogLevel.ERROR
    assert handler.should_halt


def test_single_line_span_parses() -> None:
    handler = ClingoMessageHandler("line one", stop_on_level=LogLevel.ERROR)
    handler.on_message(None, "<block>:1:3-7: warning: ordinary span")  # type: ignore[arg-type]
    assert handler.highest_level == LogLevel.WARNING
    assert not handler.should_halt


def test_multiline_message_payload_preserved() -> None:
    # gringo message payloads can span lines; the parse must not truncate them
    handler = ClingoMessageHandler("p(1).")
    handler.on_message(
        clingo.MessageCode.AtomUndefined,
        "<string>:1:1-5: info: atom does not occur in any rule head:\n  q(X)",
    )
    assert "q(X)" in handler.messages[0].message


def test_non_located_message_without_prefix_defaults_to_info() -> None:
    # No location span and no leading "word:" severity prefix: both regexes
    # fail, so severity falls back to "info" and the whole text is kept
    handler = ClingoMessageHandler("p(1).")
    handler.on_message(None, "plain message with no prefix")  # type: ignore[arg-type]
    assert handler.messages[0].severity is LogLevel.INFO
    assert handler.messages[0].message == "plain message with no prefix"


def test_format_all_messages_returns_none_when_empty() -> None:
    # With nothing captured, formatting yields None rather than a header block
    handler = ClingoMessageHandler("p(1).")
    assert handler.format_all_messages("solving") is None


def test_line_origin_adds_generated_by_note() -> None:
    origin = SourceLocation("puzzle.py", 42)
    handler = ClingoMessageHandler("p(1).\nq(X).", line_origins={2: origin})
    handler.on_message(clingo.MessageCode.Other, "<block>:2:1-5: info: something")
    formatted = handler.format_message(handler.messages[0])
    assert f"generated by {origin.display()}" in formatted


def test_line_without_origin_gets_no_note() -> None:
    # The map covers line 2 only; a message on line 1 has no origin and no
    # preceding mapped line either, so it formats without any note
    handler = ClingoMessageHandler("p(1).\nq(X).", line_origins={2: SourceLocation("puzzle.py", 42)})
    handler.on_message(clingo.MessageCode.Other, "<block>:1:1-5: info: something")
    formatted = handler.format_message(handler.messages[0])
    assert "generated by" not in formatted
    assert "generated after" not in formatted


def test_cascaded_error_names_the_nearest_preceding_origin() -> None:
    # A parse error can cascade past a malformed statement onto generated
    # framing text (e.g. a raw block missing its "." errors at "#show.");
    # the nearest mapped line above is offered as the lead
    handler = ClingoMessageHandler(
        "p(1).\nbroken(1)\n\n#show.",
        line_origins={1: SourceLocation("puzzle.py", 3), 2: SourceLocation("puzzle.py", 9)},
    )
    handler.on_message(clingo.MessageCode.Other, "<block>:4:1-6: error: syntax error")
    formatted = handler.format_message(handler.messages[0])
    assert "generated by" not in formatted
    assert "generated after puzzle.py:9" in formatted


def test_default_construction_has_no_generated_by() -> None:
    # Without a line-origins map, formatting is the plain pre-feature output
    handler = ClingoMessageHandler("p(1).\nq(X).")
    handler.on_message(clingo.MessageCode.Other, "<block>:2:1-5: info: something")
    assert "generated by" not in handler.format_message(handler.messages[0])


def test_origin_note_appears_beyond_shown_source_range() -> None:
    # Line 5 lies past the one-line source, so no snippet is shown, but the
    # origin note still lands
    origin = SourceLocation("puzzle.py", 7)
    handler = ClingoMessageHandler("p(1).", line_origins={5: origin})
    handler.on_message(clingo.MessageCode.Other, "<block>:5:1-3: error: unsafe variable")
    formatted = handler.format_message(handler.messages[0])
    assert " | " not in formatted
    assert f"generated by {origin.display()}" in formatted


def test_unlocated_message_gets_no_origin_note() -> None:
    # Messages without a location span parse to line 0, which is never a key
    # in the origins map, so no note attaches
    handler = ClingoMessageHandler("p(1).", line_origins={1: SourceLocation("puzzle.py", 3)})
    handler.on_message(clingo.MessageCode.Other, "warning: something global")
    assert handler.messages[0].line == 0
    assert "generated by" not in handler.format_message(handler.messages[0])


def test_message_carries_code_and_raw_text_for_user_dispatch() -> None:
    # code and raw_message are public surface for user-side dispatch even
    # though the library itself never reads them — pinned so they cannot
    # silently break
    program = ASPProgram()
    P = Predicate.define("p_code", ["x"])
    Q = Predicate.define("q_code", ["x"], show=False)
    program.when(Q(x=1)).derive(P(x=1))
    with pytest.raises(GroundingError) as excinfo:
        program.ground()  # q never in a head: INFO halts at the default threshold
    (carried,) = excinfo.value.messages  # the raising diagnostic rides along, structured
    assert carried.code == clingo.MessageCode.AtomUndefined
    program2 = ASPProgram()
    program2.when(Q(x=1)).derive(P(x=1))
    grounded = program2.ground(stop_on_log_level=LogLevel.ERROR)
    (message,) = grounded._message_handler.messages
    assert message.code == clingo.MessageCode.AtomUndefined
    assert "does not occur" in message.raw_message


def test_message_record_is_frozen_and_enum_typed() -> None:
    # ClingoMessage is a public record (GroundingError/Search/Model
    # .messages): frozen like every other record, severity threshold-
    # comparable as a LogLevel rather than a string to compare against
    handler = ClingoMessageHandler("p(1).")
    handler.on_message(clingo.MessageCode.Other, "warning: something odd")
    (message,) = handler.messages
    assert message.severity is LogLevel.WARNING
    assert message.severity >= LogLevel.INFO  # threshold comparison, the point of the enum
    with pytest.raises(dataclasses.FrozenInstanceError):
        message.severity = LogLevel.ERROR  # type: ignore[misc]
