"""
pyclingo's exception types.

Almost everything in pyclingo raises builtins: ValueError for invalid
programs and inputs, TypeError for wrong types, RuntimeError for misuse
guards, TimeoutError for deadlines. A class lives here only where a
builtin is too broad a catch target.
"""

from collections.abc import Sequence
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pyclingo.clingo_handler import ClingoMessage


class PyClingoError(Exception):
    """
    The root of pyclingo's dedicated exceptions. Catching it nets every
    exception CLASS pyclingo defines — not every error pyclingo raises:
    validation and misuse failures deliberately stay on builtins (see the
    module docstring).
    """


class GroundingError(PyClingoError):
    """
    clingo rejected the rendered program: a parse error, a grounding
    failure, or diagnostics at or above the stop threshold. Raised by
    ground() and every verb that grounds (solve, cautious, brave,
    optimize). The message carries clingo's diagnostics, each with a
    "generated by file:line" note pointing at the authoring Python line;
    .messages holds the same diagnostics structured (a ClingoMessage
    tuple, empty when the failure produced none).
    """

    def __init__(self, message: str, messages: Sequence[ClingoMessage] = ()) -> None:
        super().__init__(message)
        self.messages = tuple(messages)


class UnsatisfiableError(PyClingoError):
    """
    The program has no answer set, raised where an answer was required.
    The one exception reporting an OUTCOME rather than a mistake: catch
    it to branch on UNSAT, or use a verb that reports UNSAT without
    raising (solve() yields no models; cautious(), brave(), and
    optimize() return None).
    """
