"""
pyclingo's exception types.

Almost everything in pyclingo raises builtins: ValueError for invalid
programs and inputs, TypeError for wrong types, RuntimeError for misuse
guards, TimeoutError for deadlines. A class lives here only where a
builtin is too broad a catch target.
"""


class GroundingError(RuntimeError):
    """
    clingo rejected the rendered program: a parse error, a grounding
    failure, or diagnostics at or above the stop threshold. Raised by
    ground() and every verb that grounds (solve, cautious, brave,
    optimize). The message carries clingo's diagnostics, each with a
    "generated by file:line" note pointing at the authoring Python line.
    """


class UnsatisfiableError(ValueError):
    """
    The program has no answer set, raised where an answer was required.
    The one exception reporting an OUTCOME rather than a mistake: catch
    it to branch on UNSAT, or use a verb that reports UNSAT without
    raising (solve() yields no models; cautious(), brave(), and
    optimize() return None).
    """
